title: Ekansh Agrawal
email: agrawalekansh at berkeley dot edu
description: >- # this means to ignore newlines until favicon
  Hi there! Nice to meet you.
url: "https://ekanshagrawal.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  h3x4g0ns
favicon: "assets/icon.png"

markdown: kramdown
remote_theme: h3x4g0ns/no-style-please 
theme-config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "back" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show description on main page
plugins:
  - jekyll-feed
  - jekyll-seo-tag
